### ISSUE TITLE
Cant run the demo due to lack of access to the respository

### ISSUE THREAD

**Issue by zaheer-tariq** [Sitecore/docker-examples#11]
Hi,

I cannot run this demo on my machine because I do not have access to the below repository. Can you please suggest a work around?

FROM VSWebsiteRegistry.azurecr.io/sitecore:9.0.171219-xm1-cm

**Comment by jeanfrancoislarente** [comment]
My understanding is that you have to build your own Sitecore images using the docker-images repository and tag the images with your own local or remote registry. Then you can change the name of the image dependency in the docker-demo repo.
