### ISSUE TITLE
URGENT: Build is failing probably due to missing $env:SITEPATH

### ISSUE THREAD

**Issue by zaheer-tariq** [Sitecore/docker-examples#12]
Hi, 

When I run F5 for the first time it fails saying path is undefined. This is probably because I could not file $env:SITEPATH where it is defined and what value should it have? Exact error mentioned below

Urgent help will be very appreciated.

---------------------------------------------------------------------------------
1>Step 5/9 : RUN Rename-Item -Path $env:SITEPATH -NewName $env:DEFAULTWEBSITENAME;     New-Item -Path $env:SITEPATH -ItemType Directory | Out-Null;
1> ---> Running in 1ea8e628a305
Rename-Item : Cannot bind argument to parameter 'Path' because it is null.
1>At line:1 char:94
1>+ ... ference = 'SilentlyContinue'; Rename-Item -Path $env:SITEPATH -NewNam ...
1>+                                                     ~~~~~~~~~~~~~
1>    + CategoryInfo          : InvalidData: (:) [Rename-Item], ParentContainsEr
1>   rorRecordException
1>[0m[91m    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
1>[0m[91m   icrosoft.PowerShell.Commands.RenameItemCommand
1>
1>Service 'website' failed to build: The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; Rename-Item -Path $env:SITEPATH -NewName $env:DEFAULTWEBSITENAME;     New-Item -Path $env:SITEPATH -ItemType Directory | Out-Null;' returned a non-zero code: 1
1>[0m

**Comment by nickwesselman** [comment]
Closing due to updated repository purpose for Sitecore 10.
