### ISSUE TITLE
Content Delivery URL / container isn't accessible via HTTPS

### ISSUE THREAD

**Issue by ambrauer** [Sitecore/docker-examples#17]
The default Sitecore Compose file (`docker-compose.yml`) doesn't configure the `cd` service for HTTPS, but the documentation has it being accessed as such. For example: https://containers.doc.sitecore.com/docs/config-transforms#run-docker-examples. This results in a 404 when browsing https://cd.dockerexamples.localhost.

The Compose override files that include the `cd` service (`docker-compose.xm1.override.yml` and `docker-compose.xp1.override.yml`) should have this configured appropriately in Traefik for HTTPS access.

**Comment by ambrauer** [comment]
PR coming shortly (once I get access). In the meantime, the fix is to add the following to the `cd` service configuration (in the override Compose file):

```
    labels:
      - "traefik.http.routers.cd.entrypoints=websecure"
      - "traefik.http.routers.cd.tls=true"
```

**Comment by BasLijten** [comment]
@ambrauer this fix works for the CD environment. Thanks!
