### ISSUE TITLE
Sitecore Publishing Service

### ISSUE THREAD

**Issue by GoranHalvarsson** [Sitecore/docker-examples#24]
Great job!

Would be nice if you guys could create a Dockerfile(example) for Publishing Service

**Comment by jeanfrancoislarente** [comment]
Check out [PR ](https://github.com/Sitecore/docker-images/pull/348) in docker-images repo for publishing service. Includes the /modules/ps-assets as well as how to add the publishing service to sql and cm roles.

I think docker-examples is more for _using_ images rather than building them.

**Comment by nickwesselman** [comment]
When publishing service is supported in provided base images, we will add an example here.
