### ISSUE TITLE
unhealthy error. 

### ISSUE THREAD

**Issue by basselissa** [Sitecore/docker-examples#25]
I am getting these error messages at the end. do we need special license file for Sitecore 10 ?
as i used the same one of 8.x 
ERROR: for cortexprocessingworker  Container "0ee95485f65b" is unhealthy.
ERROR: for xdbautomationworker  Container "0ee95485f65b" is unhealthy.
ERROR: for xdbsearchworker  Container "0ee95485f65b" is unhealthy.
ERROR: for traefik  Container "cf6d26327a49" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by sshushliapin** [comment]
@basselissa, did you manage to solve this? I've got the same error for traefik container only.

**Comment by raskaman** [comment]
Hi, I had the same issue, I followed the steps and the unhealthy issue was gone:
1. Run docker-compose stop on Powershell.
2. Run docker-compose down on Powershell.
3. Now run iisreset /stop on Powershell to make sure that the required ports are free.
4. Now run docker-compose up -d on Powershell.
Taken from here: https://sitecore.stackexchange.com/a/26953/7724

**Comment by GeekLeo** [comment]
try run the clean.ps1 under the /docker folder
