### ISSUE TITLE
Clarify runtime environment variables

### ISSUE THREAD

**Issue by halovanic** [Sitecore/docker-examples#26]
One suggestion I have for improving the documentation and examples is to explain how Sitecore now uses [Configuration Builders](https://docs.microsoft.com/en-us/aspnet/config-builder) to source environment variables for things like connection strings and application keys when starting the site: it's not currently obvious how this works as past deployment scenarios under SIF usually involved MSDeploy transformations of the files on disk.  A developer who needs to alter something at runtime (especially if it wasn't already specifically defined in Docker Compose or Kubernetes examples) can be confused as to how some Docker Compose ENV variables are referenced during build and others at runtime.

Thanks,
Alex

**Comment by nickwesselman** [comment]
@halovanic Can you please submit this to the Sitecore docs team via docsite@sitecore.net? Thanks!
