### ISSUE TITLE
Sitecore 10.0.1 - Custom Images- Not able to bring up the containers

### ISSUE THREAD

**Issue by mvnsrpavankumar** [Sitecore/docker-examples#36]
HI Team, I am trying to use the Custom-Images with Solution Service As-Is, but not able to bring up the containers. I did not do any customization and using the exact same solution.

When tryig to bring up the containers, I see below error message in the CM and xConnect Containers.

Service 'w3svc' has been stopped
APPCMD failed with error code 259
Failed to update IIS configuration
[LOGMONITOR] INFO: Entrypoint processs exit code: -2147467259.

Could you please help me on getting this resolved as we are planning to start the Dockers development.

**Comment by nickwesselman** [comment]
This sounds like a known issue w/ LTSC2019 and 10.0.1, but please use community or official support channels for troubleshooting, and GitHub for bug reports or feature requests for the examples.
