### ISSUE TITLE
Not able to docker-compose sample images

### ISSUE THREAD

**Issue by distguitar** [Sitecore/docker-examples#40]
I followed instructions found here: 
https://doc.sitecore.com/en/developers/100/developer-tools/deploying-files-into-running-containers.html

It worked once for me. After deleting everything and starting over, I get the following errors:

PS C:\sitecore\docker-examples\custom-images> docker-compose up -d
[+] Running 32/41
 - cm Error                                                                                                        1.2s
 - hrz Pulled                                                                                                     65.7s
   - e4800203e906 Pull complete                                                                                   37.0s
   - 2ca39c593a62 Pull complete                                                                                   45.0s
   - f33de20d83fc Pull complete                                                                                   46.1s
   - 8b0ae43de5e3 Pull complete                                                                                   51.6s
   - a2725e1f8146 Pull complete                                                                                   54.6s
   - 884f009485ab Pull complete                                                                                   54.8s
   - 9d7d75acd1ca Pull complete                                                                                   55.0s
   - 7b8fec044280 Pull complete                                                                                   60.4s
   - 9bcec76a157c Pull complete                                                                                   62.1s
   - 82a370b23187 Pull complete                                                                                   62.9s
 - solution Error                                                                                                  1.2s
 - solr-init Error                                                                                                 2.3s
 - xconnect Error                                                                                                  2.3s
 - xdbsearchworker Error                                                                                           4.4s
 - traefik Pulled                                                                                                615.5s
   - 65014b3c3121 Pull complete                                                                                  409.8s
   - eac6fba788c9 Pull complete                                                                                  607.2s
   - edc29de22414 Pull complete                                                                                  607.4s
   - 4b6882ac7e42 Pull complete                                                                                  610.8s
   - 423691ba5ecc Pull complete                                                                                  613.6s
   - 84a00a51e357 Pull complete                                                                                  613.8s
   - e0d82edeef84 Pull complete                                                                                  614.0s
 - mssql Error                                                                                                     2.3s
 - solr Pulled                                                                                                   571.2s
   - 4612f6d0b889 Pull complete                                                                                  243.8s
   - f143c6fed32d Pull complete                                                                                  545.0s
   - 029f0136f9df Pull complete                                                                                  545.5s
   - 5d91b2ec93f3 Pull complete                                                                                  546.0s
   - 70f2e100a58a Pull complete                                                                                  549.5s
   - 8fc67a75e093 Pull complete                                                                                  559.5s
   - 5ee291a0b2e3 Pull complete                                                                                  562.9s
   - 2f9e91afb2ea Pull complete                                                                                  567.1s
   - 9644bd0933ff Pull complete                                                                                  567.7s
   - 90f616ea8a5a Pull complete                                                                                  568.1s
   - 48df64bdb7fd Pull complete                                                                                  568.6s
   - 595f2220d708 Pull complete                                                                                  569.1s
 - id Error                                                                                                        3.3s
 - xdbautomationworker Error                                                                                       2.3s
 - cortexprocessingworker Error                                                                                    4.4s
not implemented
PS C:\sitecore\docker-examples\custom-images>

**Comment by igneus3** [comment]
I ran into this same issue.  It looks like it is a Docker issue with the new Docker Compose V2 feature.  I disabled this feature and I was able to get past the "not implemented" error.

Reference: https://forums.docker.com/t/docker-compose-up-returns-not-implemented-what-worng/111914/11

**Comment by nickwesselman** [comment]
Yes this is a Docker Desktop issue, you need to disable Docker Compose v2.

![image](https://user-images.githubusercontent.com/27013789/144642132-e62d8398-1874-4436-b250-00454e7c204b.png)
